version: '3.0'

services:
  frontend:
    container_name: frontend
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start
    depends_on:
      - backend
    networks:
      - app-network
    restart: always
  backend:
    container_name: backend
    build:
      context: ./server
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 5000:5000
    command: npm run start:dev
    depends_on:
      - database
    networks:
      - app-network
    restart: always
  database:
    container_name: database
    image: postgres:14
    env_file:
      - ./server/.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
